language: node_js
node_js: "10"
sudo: false
env:
  CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  directories:
  - node_modules
before_install:
  - npm config set spin false
  - npm install -g npm@^6
  - export DEBUG=logdna*
install:
- npm install
- npm install -g grunt-contrib-copy
- npm install -g grunt-curl
- npm install -g grunt-eslint 
- npm install -g grunt-exec
- npm install -g grunt-line-remover
- npm install -g grunt-mocha-cli
- npm install -g grunt-zip 
- npm install --save-dev load-grunt-tasks
- npm install grunt --save-dev 
script:
- grunt test --force

# LogDNA working with Travis
